name: Publish and Release reusable workflow

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
            projectName:
                required: true
                type: string
            workingDir:
                required: true
                type: string
            releasePrefix:
                required: true
                type: string

permissions:
    contents: write
    packages: write
    pull-requests: write

jobs:
    publish-and-release:
        runs-on: ubuntu-latest

        outputs:
            new_version: ${{ steps.get_version.outputs.new_version }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.7.0
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.18.2
                  cache: 'pnpm'
                  registry-url: 'https://npm.pkg.github.com'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Bump version
              id: bump_version
              working-directory: ${{ inputs.workingDir }}
              continue-on-error: true
              run: |
                  git config user.name 'khoilen'
                  git config user.email 'khoilen@nastechglobal.com'

                  pnpm version patch || true

            - name: Get new version from package.json
              id: get_version
              working-directory: ${{ inputs.workingDir }}
              run: |
                  version=$(jq -r '.version' package.json)
                  echo "new_version=$version" >> "$GITHUB_OUTPUT"
                  echo "Bumped version: $version"

            - name: Create Pull Request for version bump
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'chore: bump ${{ inputs.releasePrefix }} to v${{ steps.get_version.outputs.new_version }}'
                  branch: release/${{ inputs.releasePrefix }}-v${{ steps.get_version.outputs.new_version }}
                  title: 'chore: bump ${{ inputs.releasePrefix }} to v${{ steps.get_version.outputs.new_version }}'
                  body: |
                      This pull request bumps the version of `${{ inputs.projectName }}` to `v${{ steps.get_version.outputs.new_version }}`.
                  author: khoilen <khoilen@nastechglobal.com>

            - name: Build lib
              run: pnpm run build
              working-directory: ${{ inputs.workingDir }}

            - name: Publish to GitHub
              run: pnpm publish
              working-directory: ${{ inputs.workingDir }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ inputs.releasePrefix }}@${{ steps.get_version.outputs.new_version }}
                  name: ${{ inputs.releasePrefix }}v${{ steps.get_version.outputs.new_version }}
                  body: |
                      ðŸ“¦ Released ${{ inputs.projectName }}v${{ steps.get_version.outputs.new_version }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
